CREATE DATABASE UniversoHerois;
Go

CREATE TABLE Heroi(
	IdHeroi UNIQUEIDENTIFIER PRIMARY KEY DEFAULT ((NEWID())), 
	Personagem VARCHAR(255) NOT NULL,
	Poder VARCHAR(50) NOT NULL,

	IdEquipes UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Equipes(IdEquipe)
);

Go

CREATE TABLE Missao(
	IdMissao UNIQUEIDENTIFIER PRIMARY KEY DEFAULT ((NEWID())), 
	Descricao VARCHAR(255) NOT NULL,

	IdEquipe UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Equipes(IdEquipe),
	IdHeroi UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Heroi(IdHeroi)
);

Go

CREATE TABLE Equipes(
	IdEquipes UNIQUEIDENTIFIER PRIMARY KEY DEFAULT ((NEWID())), 
	Nome VARCHAR(250) NOT NULL,
	BaseOperacoes VARCHAR(50) NOT NULL
);
Go